# Generated by Django 2.1 on 2018-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ref',
            field=models.CharField(default='foobar', max_length=255),
            preserve_default=False,
        ),
    ]
