# Generated by Django 2.1 on 2018-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou', '0002_entry_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
