# Generated by Django 2.1 on 2018-08-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iou', '0003_entry_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='desc',
            new_name='title',
        ),
    ]
