# Generated by Django 2.1 on 2018-08-22 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iou', '0004_auto_20180817_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('group_pk', models.IntegerField(default=-1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_info', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iou.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
