# Generated by Django 2.1 on 2018-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesentry_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesentry',
            name='html_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
