# Generated by Django 2.1 on 2018-09-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180901_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesentry',
            old_name='html_name',
            new_name='template_name',
        ),
    ]
