# Generated by Django 2.1 on 2018-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180904_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesentry',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notesentry',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
