# Generated by Django 2.1 on 2018-11-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20181006_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesentry',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
